### ISSUE TITLE
How to create a .vox file that can be read by AMAPvox?

### ISSUE THREAD

**Issue by ludwig1860** [umr-amap/AMAPVox#4]
I am a newbie for AMAPvox, I wonder how to create a .vox format file from .las format file. I didn't find any function in AMAPvox that can make this conversion. Could you please provide a bit tutorial?

**Comment by schFuelPC** [comment]
Hi ludwig1860, 
You make the vox file from running the Voxelisation process in the AMAPVox GUI. 
Parameters used in that process are detailed here: https://amapvox.org/articles/Voxelization.html

Hope that helps.

**Comment by 945fc41467** [comment]
Hello,

So, there is no way to voxelize a points cloud directly with the API ? Or maybe with another library ? If not, could you considere this as a feature request ?

Thanks
