### ISSUE TITLE
Error when running AMAPVox 2.0.0 on windows

### ISSUE THREAD

**Issue by schFuelPC** [umr-amap/AMAPVox#5]
Hi team, 
Application is awesome and really useful. 
I have just done a clean install on a windows box and have an error when executing 
`AMAPVox::run()` 

The following message appears and the GUI fails to open:
`Running AMAPVox 2.0.0
"NA" -Xms2048m --add-opens javafx.graphics/javafx.scene=ALL-UNNAMED -jar 
Warning message:
In system2(unzip, args, stdout = NULL, stderr = NULL, invisible = TRUE) :
  '"internal"' not found`
  
Any help in fixing this error is much appreciated, thanks!

**Comment by han16nah** [comment]
I am also having issues with AMAPVox 2.0.0, I am just using `AMAPVox::run(version="1.10.4")` instead (so it does not try to use the latest version)

**Comment by philippeverley** [comment]
There are several steps involved in AMAPVox::run() function:

1. check for latest version on server (presently 2.0.0)
2. download tarball to temp location
3. unzip tarball in cache directory
4. run AMAPVox

Could you please let me know whether steps 1, 2 & 3 completed successfully ? Could you please also check that `AMAPVox::getLocalVersions()` includes version 2.0.0 ?

Running command should look like `/path/to/java -Xms2048m --add-open etc.` so there is definitely a bug there to identify Java binary embedded with AMAPVox 2.0.0.

@han16nah do you have same issue than @schFuelPC with "NA" instead of a path to `java` binary ?

**Comment by han16nah** [comment]
This is the error I get when running `AMAPVox::run(version="2.0.0")`

> trying URL 'https://forge.ird.fr/api/v4/projects/421/packages/generic/amapvox/2.0.0/AMAPVox-2.0.0.zip'
Warning in utils::download.file(url, zipfile, method = "auto", mode = "wb",  :
  downloaded length 0 != reported length 27
Warning in utils::download.file(url, zipfile, method = "auto", mode = "wb",  :
  cannot open URL 'https://forge.ird.fr/api/v4/projects/421/packages/generic/amapvox/2.0.0/AMAPVox-2.0.0.zip': HTTP status was '404 Not Found'
Error in utils::download.file(url, zipfile, method = "auto", mode = "wb", : cannot open URL 'https://forge.ird.fr/api/v4/projects/421/packages/generic/amapvox/2.0.0/AMAPVox-2.0.0.zip'
Show stack trace

`AMAPVox::getLocalVersions()` does not include 2.0.0
>   version
1  1.10.4
                                                                     path
1 C:\\Users\\...\\AppData\\Local\\AMAPVox\\AMAPVox\\bin\\AMAPVox-1.10.4

**Comment by schFuelPC** [comment]
Hi @philippeverley and @han16nah ,

Thanks for your help with this - much appreciated.

In answer to your question, I think 1,2 and 3 are being completed. 
For reference this is the full error message I get when running `AMAPVox::run(version="2.0.0")`

`trying URL 'https://forge.ird.fr/api/v4/projects/421/packages/generic/amapvox/2.0.0/AMAPVox-2.0.0-windows.zip'
Content type 'application/octet-stream' length 87114856 bytes (83.1 MB)
downloaded 83.1 MB

AMAPVox 2.0.0 successfully installed in C:\Users\...\AppData\Local\AMAPVox\AMAPVox\bin\AMAPVox-2.0.0-windows
Running AMAPVox 2.0.0
"NA" -Xms2048m --add-opens javafx.graphics/javafx.scene=ALL-UNNAMED -jar 
Warning message:
In system2(unzip, args, stdout = NULL, stderr = NULL, invisible = TRUE) :
  '"internal"' not found`


`AMAPVox::getLocalVersions()` does not include 2.0.0
`  version                                                                          path
1  1.10.4 C:\\Users\\...\\AppData\\Local\\AMAPVox\\AMAPVox\\bin\\AMAPVox-1.10.4`

**Comment by han16nah** [comment]
@philippeverley 
Correct, thanks. Now after updating the AMAPVox R package, I get the same error as @schFuelPC with "NA" instead of the path to the java binary

> Check for updates. Latest version available 2.0.0
> trying URL 'https://forge.ird.fr/api/v4/projects/421/packages/generic/amapvox/2.0.0/AMAPVox-2.0.0-windows.zip'
> Content type 'application/octet-stream' length 87114856 bytes (83.1 MB)
> downloaded 83.1 MB
> 
> AMAPVox 2.0.0 successfully installed in C:\Users\...\AppData\Local\AMAPVox\AMAPVox\bin\AMAPVox-2.0.0-windows
> Running AMAPVox 2.0.0
> "NA" -Xms2048m --add-opens javafx.graphics/javafx.scene=ALL-UNNAMED -jar

**Comment by schFuelPC** [comment]
Hi @philippeverley and @han16nah , 
Just wanted to let you know that I ran AMAPvox on a linux box running Ubuntu 22.04 ie `AMAPVox::run(version="2.0.0")` and it opened the application successfully so it appears it might be a windows issue potentially?

Thanks

**Comment by philippeverley** [comment]
Thanks to both of you for your patience. Unzipping of the downloaded AMAPVox tarball on Windows was not working as expected, so AMAPVox consequently failed to run.
Fixed with release v1.0.1. On its way to CRAN. Waiting for acceptance on CRAN before tagging the release on Github. Sorry for taking so long in fixing it, last weeks were very busy.

**Comment by schFuelPC** [comment]
That's awesome, thanks for your work on this @philippeverley

**Comment by philippeverley** [comment]
AMAPVox 1.0.1 is on CRAN, at least 
https://cran.r-project.org/web/packages/AMAPVox/index.html
